### ISSUE TITLE
Add new maintainers

### ISSUE THREAD

**Issue by brauliobo** [slim-template/jekyll-slim#6]
The gem is quite outdated and don't even work with jekyll 3 (https://github.com/slim-template/jekyll-slim/issues/4). Please add new maintainers to release new versions.

**Comment by donv** [comment]
I am using this gem with Jekyll 3 with some modifications.  I have making a new compatible release on my plan, but no time table.

Motivation and pull requests welcome  😄

**Comment by donv** [comment]
I have tentatively put making a new release on my plan for next week.

**Comment by brauliobo** [comment]
@donv this fork worked fine for me https://github.com/kesha-antonov/jekyll-slim

**Comment by brauliobo** [comment]
Applied a fix for layouts support, https://github.com/olery/jekyll-slim. I might help maintaining if you need :)

**Comment by Bilge** [comment]
How do you use a fork?

**Comment by mkhairi** [comment]
any update?

**Comment by donv** [comment]
@minad Can you activate travis-ci builds or give me access to enable it?

**Comment by minad** [comment]
@donv I enabled it. I also added you to admins.
